version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cerebro_db
    restart: always
    environment:
      POSTGRES_USER: cerebro_admin
      POSTGRES_DB: cerebro_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "6543:5432"
    volumes:
      - cerebro_data_v2:/var/lib/postgresql/data

volumes:
  cerebro_data_v2:
